---
title: "About"
bibliography: references.json
---

## 2026

Strive for calm and flow in both practice and performance. Allow progress to naturally unfold through relaxed, deliberate work.

-   Protect your body by maintaining a relaxed posture, using a light grip, incorporating a brief daily warm-up and stretching routine, and taking regular breaks.
-   Train your mind by engaging in daily improvisation with constraints and studying a small piece of jazz theory to apply it to a standard.
-   Perform daily, record weekly. Reframe nerves as energy, conclude sessions with free playing, and build up from low-pressure performances.
-   Use a slow metronome, stay hydrated, take short breaks, and incorporate meditation before performance videos.
-   Keep it simple and consistent: Dedicate one focused hour daily.
    -   **Warm-Up (10 minutes):** Begin with a warm-up.
    -   **Technique (15 minutes):** Focus on technique.
    -   **Theory (15 minutes):** Apply theory to your practice.
    -   **Improvisation (10 minutes):** Allow yourself to improvise.
    -   **Repertoire (10 minutes):** Develop and sustain a setlist of songs.

Maintain relaxation, practice daily with clear boundaries, apply theory immediately, and perform regularly, even in small ways.

## 2025

Practice with discipline, but without friction, maintaining a calm and steady approach. Take each step deliberately to enter the flow state where progress unfolds. Though progress is not the goal, it arises as a consequence of unintended outcomes. This is the ultimate state of mind, the one that brings true contentment.

> Learning to play the guitar physically requires patience. Practice slowly to maintain an even tempo. Don’t skip or rush anything. Don’t try to perfect each lesson before moving on. Playing technique improves with practice. Reviewing previously studied material will seem easier each time. (Slow, steady practice and constant review will eventually lead to speed and accuracy.) - @leavitt2020

### Physical Techniques

Keep good posture and light grip. Warm up 10 minutes with slow exercises. Do daily stretches and short breaks.

### Theoretical Development

Practice improvisation daily with limits, backing tracks, mental images, and recordings. Study jazz theory daily (like modal interchange and altered scales) on standards.

### Performance

Turn anxiety into excitement with breathing and new thinking. End sessions with free playing. Try small performances step by step.

### Integration

Practice for 60 minutes daily: 10 minutes warm-up, 15 minutes technique, 15 minutes theory, and 10 minutes improvisation. Use a slow metronome, take breaks, stay hydrated, and include 10 minutes of meditation for relaxation.

## 2024

Following are the guidelines for 2024, from @denk2022

-   Practice phrasing.

-   Don't be a perfectionist, it's a deadly weakness.

-   Get the mechanics of performing right by way of **correct posture, fingering and breathing**.

-   **Learn to practice right:** Mechanics, play with your brain and discover meaning in the music you play.

-   Listen and learn pieces well enough to describe it in your own words, use metaphors like the master [György Sebők](https://en.wikipedia.org/wiki/György_Sebők) did. When you perform the music, let your metaphors guide you.

-   Harmony and melody are sacred but rhythm is where you can exercise your freedom.

-   If a note is wrong, you're only one fret away from it, just shift your finger, and you've arrived at the right note.

-   Emulate [Paul Desmond](https://en.wikipedia.org/wiki/Paul_Desmond)'s sound: a light, melodic tone on the alto saxophone, **like a dry martini**.

## 2023

> Practice any art, music, singing, dancing, acting, drawing, painting, sculpting, poetry, fiction, essays, reportage, no matter how well or badly, not to get money and fame, but to experience becoming, to find out what's inside you, to make your soul grow. - Kurt Vonnegut

-   Eliminate or minimize distraction.

-   Consolidate songs and add music to next album "... from Hokkaido to Okinawa..."

-   Practice diligently and relaxed.

-   Use metronome.

-   Strive for good tone.

-   Improve technique.

-   Learn standard music notation.

-   The ultimate goal: To make good music at every stage of your development.